services:
  kokoro:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.4-master@sha256:03a5201c0327f1f1a1619ebbd9722e3b5477b0cccc588aaddb74dd89aad67f15
    container_name: kokoro
    labels:
      yantra.name: "Kokoro"
      yantra.logo: "Qmc3MXRpboBnU5sBsyDAyMGvaPge5vTbEwfFN3P13R5q5Z"
      yantra.category: "ai"
      yantra.port: "8880 (HTTP - Web UI)"
      yantra.description: "Lightweight Text-to-Speech model with 82M parameters delivering high-quality speech synthesis"
      yantra.website: "https://github.com/remsky/Kokoro-FastAPI"
    ports:
      - "8880"
    user: "1000:1000"
    restart: unless-stopped
