services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Optional, only if you want docker integration
      - homarr_data:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${HOMARR_ENCRYPTION_KEY:-2dff4b06831e4608cc93dfee6fbe55b29ff0ee189cafd23ccc128698dae55884}
    ports:
      - "7575"
    labels:
      yantr.name: "Homarr"
      yantr.logo: "QmXrjcV7SukGrmAgqF3tHVCu2LTYYGkhADumKY74AHzLf4"
      yantr.description: "Modern customizable dashboard with 30+ integrations and 10K+ icons"
      yantr.category: "dashboard,tools"
      yantr.port: "7575 (HTTP - Web UI)"
      yantr.website: "https://github.com/homarr-labs/homarr"

volumes:
  homarr_data:
