services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    labels:
      yantr.name: "Stirling-PDF"
      yantr.logo: "QmZ6nmAP1oSgpfd4N7oAYNEJrRqgQTPGndZPyN2vwmyjBE"
      yantr.category: "tools,utility"
      yantr.port: "8080 (HTTP - Web UI)"
      yantr.description: "Powerful locally hosted web-based PDF manipulation tool"
      yantr.website: "https://github.com/Stirling-Tools/Stirling-PDF"
    ports:
      - "8080"
    volumes:
      - stirling_pdf_data:/usr/share/tessdata
      - stirling_pdf_config:/configs
    environment:
      DOCKER_ENABLE_SECURITY: ${STIRLING_PDF_SECURITY:-false}
      SYSTEM_DEFAULTLOCALE: ${STIRLING_PDF_LOCALE:-en-US}
    restart: unless-stopped

volumes:
  stirling_pdf_data:
  stirling_pdf_config:
