services:
  domain-locker:
    image: lissy93/domain-locker:latest
    container_name: domain-locker
    hostname: domain-locker
    volumes:
      - domain_locker_data:/app/data
    ports:
      - "3000"
    restart: unless-stopped
    labels:
      yantra.name: "Domain Locker"
      yantra.category: "security,tools"
      yantra.port: "3000 (HTTP - Web UI)"
      yantra.description: "Complete visibility of your domain portfolio with monitoring and alerts"
      yantra.website: "https://domain-locker.com"

volumes:
  domain_locker_data:
