services:
  domain-locker:
    image: lissy93/domain-locker:latest
    container_name: domain-locker
    hostname: domain-locker
    volumes:
      - domain_locker_data:/app/data
    ports:
      - "3000"
    restart: unless-stopped
    labels:
      yantr.name: "Domain Locker"
      yantr.logo: "QmXCFhWvYYmz21YHP38zFFxsitmvMeZStbjfacg2dKrZnw"
      yantr.category: "security,tools"
      yantr.port: "3000 (HTTP - Web UI)"
      yantr.description: "Complete visibility of your domain portfolio with monitoring and alerts"
      yantr.website: "https://domain-locker.com"

volumes:
  domain_locker_data:
