services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    environment:
      AUTO_UPDATE: "true"
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - "9117"
    restart: unless-stopped
    labels:
      yantr.name: "Jackett"
      yantr.logo: "QmQs2oSE9ccQrueSFPw6ZPXCVHk2rFuT54HUyZAApSoqDJ"
      yantr.category: "media,tools,utility"
      yantr.port: "9117 (HTTP - Web UI)"
      yantr.description: "API proxy for torrent trackers with Sonarr/Radarr support."
      yantr.website: "https://github.com/Jackett/Jackett"

volumes:
  jackett_config:
  jackett_downloads:
