services:
  dashmachine:
    image: rmountjoy/dashmachine:latest
    container_name: dashmachine
    labels:
      yantr.name: "Dashmachine"
      yantr.logo: "QmTvbLNZMCyEQmcFBbY7EkKq9hnJTPy8ut4hAYRH3Xxaiw"
      yantr.category: "dashboard,organization"
      yantr.port: "5000 (HTTP - Web UI)"
      yantr.description: "Customizable personal dashboard for organizing links and services"
      yantr.website: "https://github.com/rmountjoy92/dashmachine"
    ports:
      - "5000"
    volumes:
      - dashmachine_data:/dashmachine/dashmachine/user_data
    restart: unless-stopped

volumes:
  dashmachine_data:
