services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    labels:
      yantr.name: "Watchtower"
      yantr.logo: "QmXGn6c1UzVGBQmuxcikBush4KYdM2KASxggR8Z7rH7kw4"
      yantr.category: "tools,utility"
      yantr.description: "Automatically update running Docker containers"
      yantr.website: "https://containrrr.dev/watchtower"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_API_VERSION: "1.44"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_SCHEDULE: "0 */3 * * *"
    restart: unless-stopped
