services:
  emby:
    image: linuxserver/emby:latest
    container_name: emby
    volumes:
      - emby-config:/config
      - emby-media:/data
    ports:
      - "8096"
    restart: unless-stopped
    labels:
      yantra.name: "Emby"
      yantra.logo: "QmQW3NWmVuq3Q76pibyTu2XAkzLfWVKCeSKNcywmNwXGUV"
      yantra.category: "media,entertainment"
      yantra.port: "8096 (HTTP - Web UI)"
      yantra.description: "Media server for streaming video, music, live TV, and photos"
      yantra.website: "https://emby.media/"

volumes:
  emby-config:
    name: emby-config
  emby-media:
    name: emby-media
