services:
  web-check:
    image: lissy93/web-check:latest
    container_name: web-check
    ports:
      - "3000"
    restart: unless-stopped
    labels:
      yantr.name: "Web Check"
      yantr.logo: "QmXwF1DUNZLpkLFzK7HhVdtNNPncNZMS4ktb7KHb6K8Khz"
      yantr.category: "tools,network,utility"
      yantr.port: "3000 (HTTP - Web UI)"
      yantr.description: "All-in-one tool for analyzing and monitoring websites"
      yantr.website: "https://github.com/lissy93/web-check"
