services:
  bitmagnet:
    image: ghcr.io/bitmagnet-io/bitmagnet:v0.10
    container_name: bitmagnet
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - "3333"
      - "3334/tcp"
      - "3334/udp"
    environment:
      HOME: /tmp
      XDG_CONFIG_HOME: /config
      TZ: ${TZ:-UTC}
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresx
      POSTGRES_NAME: bitmagnet
    volumes:
      - bitmagnet_config:/config/bitmagnet
    command:
      - worker
      - run
      - --keys=http_server
      - --keys=queue_server
      - --keys=dht_crawler
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      yantr.name: "Bitmagnet"
      yantr.logo: "QmX2bA23zVjnxGeQgwUfv3XXuascGnnBX33ap7CWWknrXP"
      yantr.category: "media,tools,utility"
      yantr.port: "3333 (HTTP - Web UI)"
      yantr.description: "Self-hosted BitTorrent indexer, DHT crawler, and torrent client."
      yantr.website: "https://bitmagnet.io"

  postgres:
    image: postgres:16-alpine
    container_name: bitmagnet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgresx
      POSTGRES_DB: bitmagnet
      POSTGRES_USER: postgres
    shm_size: 1g
    volumes:
      - bitmagnet_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 20s
      interval: 10s

volumes:
  bitmagnet_config:
  bitmagnet_db:
