services:
  element:
    image: vectorim/element-web:latest
    container_name: element
    labels:
      yantra.name: "Element"
      yantra.logo: "QmWMcjdA7izomrqwuW6D8JT8y75K7jCANqnDMYxZRzmzHU"
      yantra.category: "productivity,security"
      yantra.port: "80 (HTTP - Web UI)"
      yantra.description: "Secure and decentralized Matrix chat client for communication"
      yantra.website: "https://element.io"
    ports:
      - "80"
    volumes:
      - element_config:/app/config
    restart: unless-stopped

volumes:
  element_config:
