services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    labels:
      yantr.name: "MariaDB"
      yantr.logo: "Qmegk86ebzbktv7YWCMnVrueBpfpZHm9wktuUSdQBHvHQx"
      yantr.category: "database,storage"
      yantr.port: "3306 (TCP - Database)"
      yantr.description: "Open-source relational database compatible with MySQL"
      yantr.website: "https://github.com/MariaDB/server"
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
