services:
  trip:
    image: ghcr.io/itskovacs/trip:latest
    container_name: trip
    labels:
      yantr.name: "Trip"
      yantr.logo: "QmcxepcQDfmK7gcGSdWPNuyFR1oqR4qeG5jvetn2qYHg8z"
      yantr.category: "productivity,tools"
      yantr.port: "8000 (HTTP - Web UI)"
      yantr.description: "Self-hostable map tracker and trip planner to visualize POIs and organize your next adventure"
      yantr.website: "https://github.com/itskovacs/trip"
    ports:
      - "8000"
    volumes:
      - trip_storage:/app/storage
    restart: unless-stopped

volumes:
  trip_storage:
