

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    ports:
      - "80"
    restart: unless-stopped
    labels:
      yantr.name: "Whoami"
      yantr.logo: "QmZvfwKJRMrMvzUyRyrLJjShVCsGozSAPDrCq6Vg1Fpde5"
      yantr.category: "tools,utility"
      yantr.port: "80 (HTTP - Web UI)"
      yantr.description: "Tiny HTTP service that prints system information - perfect for testing"
      yantr.website: "https://github.com/traefik/whoami"

