services:
  drupal:
    image: drupal:latest
    container_name: drupal
    labels:
      yantr.name: "Drupal"
      yantr.logo: "QmXryrL9jF3YL37TEs7eZRsv5mvDyUYSkWdPrEDKE8GM8k"
      yantr.category: "cms,productivity"
      yantr.port: "80 (HTTP - Web UI)"
      yantr.description: "Powerful open-source content management system for building websites"
      yantr.website: "https://github.com/drupal/drupal"
    ports:
      - "80"
    volumes:
      - drupal_html:/var/www/html
    restart: unless-stopped

volumes:
  drupal_html:
