services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    labels:
      yantra.name: "MongoDB"
      yantra.logo: "QmSu7is9ZSvhmrtCgi3J1uHTCkNzLuvAEbCbeXsMLuqzr6"
      yantra.category: "database,storage"
      yantra.port: "27017 (TCP - Database)"
      yantra.description: "NoSQL document database for flexible data storage and management"
      yantra.website: "https://github.com/mongodb/mongo"
    ports:
      - "27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
