services:
  zeronote:
    image: ghcr.io/besoeasy/zeronote:main
    container_name: zeronote
    hostname: zeronote
    volumes:
      - zeronote_data:/app/data
    ports:
      - "8000"
    restart: unless-stopped
    labels:
      yantr.name: "ZeroNote"
      yantr.logo: "Qmbdks6yn4TrP2hfFZJ1dZPW84kYhrWoXDj4tLBtpWfRiF"
      yantr.category: "productivity,security"
      yantr.port: "8000 (HTTP - Web UI)"
      yantr.description: "Offline-first encrypted notes application."
      yantr.website: "https://github.com/besoeasy/zeronote"

volumes:
  zeronote_data:
