services:
  originless:
    image: ghcr.io/besoeasy/originless:main
    container_name: originless
    hostname: originless
    environment:
      - STORAGE_MAX=${STORAGE_MAX:-200GB}
    volumes:
      - originless:/app/data
    ports:
      - "3232"
      - "4001" # Swarm TCP
      - "4001/udp" # Swarm UDP
    restart: unless-stopped
    labels:
      yantra.name: "Originless"
      yantra.logo: "QmNPv75ULMPbZZiZsnrBx3h51onDfNBUoK84PDRKEg1GGT"
      yantra.category: "utility,tools"
      yantra.port: "3232 (HTTP - Web UI)"
      yantra.description: "One all-in-one storage backend you can drop into anything: your own apps, screenshot tools, pastebin-style pastes, Nostr clients, Reddit posts, forum embedsâ€”anything that needs durable, anonymous file hosting. One Originless to rule them all and keep you anonymous."
      yantra.website: "https://github.com/besoeasy/originless"

volumes:
  originless:
