services:
  libreddit:
    image: ceramicwhite/libreddit:0.22.9@sha256:00a133da4ae8eb1b7d3ce9af0ca387e2dd929dc6b490736532b5d998a025c362
    container_name: libreddit
    labels:
      yantra.name: "LibReddit"
      yantra.logo: "QmTieAKkWAmA12gchbEJiBGZZK64hsuKQYRtSbibJ9qWxF"
      yantra.category: "social,privacy"
      yantra.port: "7420 (HTTP - Web UI)"
      yantra.description: "Private Reddit front-end written in Rust with no JavaScript, ads, or tracking"
      yantra.website: "https://github.com/spikecodes/libreddit"
    ports:
      - "7420"
    environment:
      - PORT=7420
    init: true
    restart: unless-stopped
