services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${WEBPASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    labels:
      yantr.name: "MinIO"
      yantr.logo: "QmWgS8CxKS7UYSgNNp6nqsTLYwMF5tk8cQfroTgyvxsbQ7"
      yantr.category: "utility,tools"
      yantr.port: "9001 (HTTP - Console), 9000 (HTTP - API)"
      yantr.description: "High Performance Object Storage compatible with Amazon S3 API"
      yantr.website: "https://min.io"

volumes:
  minio_data:
