services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    labels:
      yantr.name: "Glances"
      yantr.logo: "QmVa2UDC7pALhMyoiXgQsThyF9QszT2f7WcK168k7AGXhf"
      yantr.category: "monitoring,tools"
      yantr.port: "61208 (HTTP - Web UI)"
      yantr.description: "Real-time system monitoring for containers and host metrics"
      yantr.website: "https://nicolargo.github.io/glances/"
    ports:
      - "61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: "host"
    environment:
      GLANCES_OPT: -w
    restart: unless-stopped
