services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate --protocol http2 run --token ${TUNNEL_TOKEN}
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    restart: unless-stopped
    labels:
      yantra.name: "Cloudflared"
      yantra.logo: "Qmcyr4xpG4SZdBp9VorVjRrvHqHoQzCu9YHCQZGNC5ck8T"
      yantra.category: "network,security"
      yantra.description: "Cloudflare Tunnel for secure remote access without exposing ports"
      yantra.website: "https://github.com/cloudflare/cloudflared"
