services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: always
    tty: true
    stdin_open: true
    ports:
      - "25565"
    environment:
      EULA: ${EULA:-TRUE}
      TYPE: ${TYPE:-VANILLA}
      VERSION: ${VERSION:-LATEST}
      MEMORY: ${MEMORY:-1G}
      DIFFICULTY: ${DIFFICULTY:-normal}
      MODE: ${MODE:-survival}
      MAX_PLAYERS: ${MAX_PLAYERS:-20}
      MOTD: ${MOTD:-A Minecraft Server}
    volumes:
      - minecraft-data:/data
    restart: unless-stopped
    labels:
      yantr.name: "Minecraft Server"
      yantr.logo: "QmPB7iXHMAu3Wor5jiEsoifm5tZyMEUojhbj6TJJefsY7s"
      yantr.category: "gaming"
      yantr.port: "25565 (TCP - Game Server)"
      yantr.description: "Open-source sandbox game server with endless possibilities"
      yantr.website: "https://docker-minecraft-server.readthedocs.io/"

volumes:
  minecraft-data:
