services:
  tor-browser:
    image: domistyle/tor-browser
    container_name: tor-browser
    ports:
      - "5800"
    labels:
      yantr.name: "Tor Browser"
      yantr.logo: "QmaVTPSKHnzenoUpqydsnNHQ45WJDtRxxjnqzVqK4MiB38"
      yantr.description: "Privacy-focused web browser with Tor network integration"
      yantr.category: "privacy,security"
      yantr.port: "5800 (HTTP - Web UI)"
      yantr.website: "https://github.com/domistyle/docker-tor-browser"
